version: '3.3'
services:
  web:
    build: ./app/
    ports:
      - "3001:3000" # Run locally on 3001
    volumes:
      - ./app/:/opt/
  mysqldb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'shortr'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - shortr-db:/var/lib/mysql
volumes:
  shortr-db:

